version: "3"
services:
  email:
    build: ./email
    ports: 
      - 10000:10000
    
  server:
    build: ./server
    ports: 
      - 9997:9997
    links:
      - email

  front:
    build: ./front/front-app
    ports: 
      - 3000:3000